### ISSUE TITLE
ReferenceError

### ISSUE THREAD

**Issue by raisiqueira** [pie6k/react-native-dev-menu-on-touch#2]
Hi. I'm using this lib, but when i run the app, return this error:

```
ReferenceError: Can't find variable: React
```

**Comment by pie6k** [comment]
Wherever you create react tag like `<Something/>` you need react to be imported like `import React from 'react';` in the same file. It has nothing to do with lib itself :)

**Comment by Va1iant** [comment]
mine too.. I tried to encapsulate my main app tags with DevMenuOnTouch and only then
![WhatsApp Image 2019-07-17 at 8 13 04 AM](https://user-images.githubusercontent.com/3322672/61340045-ce245c80-a86a-11e9-81d3-abc4a8f649e6.jpeg)
 it triggers the error
